apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-client-config
  namespace: <NAMESPACE>
data:
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://service-discovery.<NAMESPACE>.svc.cluster.local:8761/eureka/"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config.<NAMESPACE>.svc.cluster.local:9296"
  SPRING_PROFILES_ACTIVE: "<PROFILE>"
  SPRING_ZIPKIN_BASE_URL: "http://zipkin.<NAMESPACE>.svc.cluster.local:9411/"

